myproject/urls.py
from django.conf.urls import url
from django.contrib import admin
from myproject.views import generate_schedule, homepage, update_pto, request_day, remove_day
from myproject.views import see_call_day_count 
from django.conf.urls import include

urlpatterns = [
    url(r'^$', homepage),
    url(r'^admin/', admin.site.urls),
    url('^', include('django.contrib.auth.urls')),
    url(r'^schedule/(\d{4})/(\d{1,2})/$', generate_schedule, name='schedule'),
    url(r'^pto/(\d{4})/(\d{1,2})/$', update_pto, name='pto'),
    url(r'^request/(\d{1,2})/(\d{4})/(\d{1,2})/(\d{1,2})/$', request_day),
    url(r'^remove/(\d{1,2})/(\d{4})/(\d{1,2})/(\d{1,2})/$', remove_day),
    url(r'^calldaycount/$', see_call_day_count),
]

scheduler/models.py
from django.db import models
from django.conf import settings

# Requested day off by resident
class DayOff(models.Model):
    date = models.DateField(verbose_name="PTO Date")
    def __str__(self):
        return u'%s %s, %s' % (self.date.strftime("%B"), self.date.day, self.date.year)

# Resident centric database 
class Resident(models.Model):
    YEAR_RES_CHOICES = (
            (1, 'PGY1'),
            (2, 'PGY2'),
            (3, 'PGY3'),
            (4, 'PGY4'),
            (5, 'PGY5'),
    )
    fname = models.CharField(max_length=50, verbose_name="First Name", blank=True)
    lname = models.CharField(max_length=50, verbose_name="Last Name", blank=True)
    name = models.CharField(max_length=50, verbose_name="Resident Name", blank=True)
    year = models.IntegerField(choices = YEAR_RES_CHOICES, verbose_name="Year of Service")
    PTO = models.ManyToManyField(DayOff, verbose_name="PTO Requested Days", blank=True)
    noCallDays = models.IntegerField(default=0, verbose_name="Number of Call Days")
    noWkndCallDays = models.IntegerField(default=0,verbose_name="Number of Weekend Call Days")
    resType = models.CharField(max_length=16, blank=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, blank=True, null=True)

    # Auto write junior or senior
    def save(self, *args, **kwargs):
        self.resType = "Senior" if self.year >= 3 else "Junior"
        super(Resident, self).save(*args, **kwargs)

    def __str__(self):
        return u'%s, %s - PGY%s' % (self.lname, self.fname, self.year)

# Service that residents can be on
class Service(models.Model):
    MONTH_CHOICES = (
            (1,"January"),(2,"February"),
            (3,"March"),(4,"April"),
            (5,"May"),(6,"June"),
            (7,"July"),(8,"August"),
            (9,"September"),(10,"October"),
            (11,"November"),(12,"December"),
    )
    SERVICE_CHOICES = (
            (1,"Trauma"),(2,"Hepatobiliary / Transplant"),
            (3,"Vascular"),(4,"Colorectal"),
            (5,"Breast"),(6,"Gen Surg - Gold"),
            (7,"Gen Surg - Blue"),(8,"Gen Surg - Orange"),
            (9,"Plastics"),(10,"PCH"),
            (11,"Thoracic"),(12,"Anesthesia / IR"),
            (13,"Critical Care"), (14, "Harding"), (15,"Other"),
    )
    YEAR_CHOICES = (
            (2017, 2017), (2018, 2018), (2019, 2019),
    )
    month = models.IntegerField(choices = MONTH_CHOICES, verbose_name="Month of Year") 
    year = models.IntegerField(choices = YEAR_CHOICES, verbose_name="Year")
    onservice = models.IntegerField(choices = SERVICE_CHOICES, verbose_name ="Service")
    res = models.ForeignKey(Resident, verbose_name="Resident on Service")
    callDays = models.IntegerField(default=0, verbose_name="Call Days This Month")
    callDaysYTD = models.IntegerField(default=0, verbose_name="Call Days YTD")
    wkndcallDays = models.IntegerField(default=0, verbose_name="Weekend Call Days This Month")
    wkndcallDaysTYD = models.IntegerField(default=0, verbose_name="Weekend Call Days YTD")

    def __str__(self):
        return u'%s %s' % (self.month, self.onservice)

# Individual day of call schedule - this is all we need for schedule storing!
class Day(models.Model):
    date = models.DateField(verbose_name="On Call Day")
    residents = models.ManyToManyField(Resident, verbose_name="Residents on Call", blank=True) 

    def get_residents(self):
        return "\n".join([r.lname for r in self.residents.all()])

templates/CallCount.html
{% extends "base.html" %}

{% block css %}
<link href='http://fonts.googleapis.com/css?family=PT+Sans:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=PT+Sans+Narrow:400,700' rel='stylesheet' type='text/css'>

<style>

/*body {
    line-height: 1;
    margin: 50px;
}*/

div.schedule {
    background: rgba(0, 0, 0, .1);
    border-radius: 5px;
    box-sizing: border-box;
    padding: 15px;
    width: 600px;
    float:left;
    margin-top:50px;
    margin-left:50px;
}

div.key {
    border-radius: 5px;
    box-sizing: border-box;
    padding: 10px;
    margin-left: 20px;
    margin-top:30px;
    float:left;
}

header {
    overflow: clear;
    position: relative;
}

h2 {
    font-family: 'PT Sans Narrow', sans-serif;
    font-size: 18px;
    font-weight: 700;
    margin: 0 0 10px;
    text-align: center;
}

button {
    position: absolute;
    top: -4px;
}

button:first-child {
    left: 0;
}

button:last-child {
    right: 0;
}

table {
    background: #fff;
    border-collapse: collapse;
    color: #222;
    font-family: 'PT Sans', sans-serif;
    font-size: 13px;
    width: 40%;
}

td {
    border: 1px solid #ccc;
    color: #444;
    line-height: 22px;
    text-align: center;
    height: 20px;
    width: 60px;
    vertical-align: text-top;
    padding-top: 6px;
    padding-bottom: 5px;
}

tr:first-child td {
    color: #222;
    font-weight: 700;
}

.selected {
    background: #f0951d;
    border: 0;
    box-shadow: 0 2px 6px rgba(0, 0, 0, .5) inset;
}

/* Anesthesia + IR */
span.Anesthesia {
    background-color: #ffffff; 
}

/* Trauma */
span.Trauma {
    background-color: red;
}

/* Hepato */
span.Hepatobiliary {
    background-color: #9ACD32;
}

/* Orange */
span.Orange {
    background-color: orange;
}

/* Blue */
span.Blue {
    background-color: #6495ED;
}

/* Gold */
span.Gold {
    background-color: gold;
}

/* Breast */
span.Breast {
    background-color: #FF69B4;
}

/* Breast */
span.Colorectal {
    background-color: #000000;
    color: #ffffff;
}

/* PCH */
span.PCH {
    background-color: #BA55D3;
}

/* Vascular */
span.Vascular {
    background-color: #FFE4C4;
}

/* Harding */
span.Harding {
    background-color: #008B8B;
}

</style>

{% endblock css %}

{% block title %}PTO Requests{% endblock title %}

{% block content %}

<br /><h2>Call Days per Resident - Year to Date</h2><br />

<table align="center">
    <tr>
        <th>Resident</th>
        <th>Weekdays</th>
        <th>Weekends (F/Sa/Su)</th>
    </tr>

{% for res, calldays in ResDict.items %}

{% if not res.name == "Trauma Mayo" %}
<tr>
    <td>{{res.name}}</td>
    <td>{{calldays.0}}</td>
    <td>{{calldays.1}}</td>
</tr>
{% endif %}

{% endfor %}

</table>

{% endblock content %}

templates/PTO.html
{% extends "base.html" %}

{% block css %}
<link href='http://fonts.googleapis.com/css?family=PT+Sans:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=PT+Sans+Narrow:400,700' rel='stylesheet' type='text/css'>

<style>

/*body {
    line-height: 1;
    margin: 50px;
}*/

div.schedule {
    background: rgba(0, 0, 0, .1);
    border-radius: 5px;
    box-sizing: border-box;
    padding: 15px;
    width: 600px;
    float:left;
    margin-top:50px;
    margin-left:50px;
}

div.key {
    border-radius: 5px;
    box-sizing: border-box;
    padding: 10px;
    margin-left: 20px;
    margin-top:30px;
    float:left;
}

header {
    overflow: clear;
    position: relative;
}

h2 {
    font-family: 'PT Sans Narrow', sans-serif;
    font-size: 18px;
    font-weight: 700;
    margin: 0 0 10px;
    text-align: center;
}

button {
    position: absolute;
    top: -4px;
}

button:first-child {
    left: 0;
}

button:last-child {
    right: 0;
}

table {
    background: #fff;
    border-collapse: collapse;
    color: #222;
    font-family: 'PT Sans', sans-serif;
    font-size: 13px;
    width: 100%;
}

td {
    border: 1px solid #ccc;
    color: #444;
    line-height: 22px;
    text-align: center;
    height: 50px;
    width: 60px;
    vertical-align: text-top;
    padding-top: 6px;
    padding-bottom: 5px;
}

tr:first-child td {
    color: #222;
    font-weight: 700;
}

.selected {
    background: #f0951d;
    border: 0;
    box-shadow: 0 2px 6px rgba(0, 0, 0, .5) inset;
}

/* Anesthesia + IR */
span.Anesthesia {
    background-color: #ffffff; 
}

/* Trauma */
span.Trauma {
    background-color: red;
}

/* Hepato */
span.Hepatobiliary {
    background-color: #9ACD32;
}

/* Orange */
span.Orange {
    background-color: orange;
}

/* Blue */
span.Blue {
    background-color: #6495ED;
}

/* Gold */
span.Gold {
    background-color: gold;
}

/* Breast */
span.Breast {
    background-color: #FF69B4;
}

/* Breast */
span.Colorectal {
    background-color: #000000;
    color: #ffffff;
}

/* PCH */
span.PCH {
    background-color: #BA55D3;
}

/* Vascular */
span.Vascular {
    background-color: #FFE4C4;
}

/* Harding */
span.Harding {
    background-color: #008B8B;
}

</style>

{% endblock css %}

{% block code %}

    <script>

        $(document).ready(function(){
            $(':checkbox').change(function() {
            // this will contain a reference to the checkbox   
                if (this.checked) {
                    var webstr = "http://stjoesscheduler.com/request/{{user.id}}/" + this.value + "/" + this.name + "/";
                    $.get(webstr); 
                } else {
                    var webstr = "http://stjoesscheduler.com/remove/{{user.id}}/" + this.value + "/" + this.name + "/";
                    $.get(webstr); 
                }
            });
        });

    </script>

{% endblock code %}

{% block title %}PTO Requests{% endblock title %}

{% block content %}

<br />
<div style="padding-left:5em;">Select requested PTO days. Days are input or deleted automatically. No need to submit.</div>

{% for year, month, monthName, cal, PTO in ymnamescals %} 

    {% if not forloop.first %}

    <div class="schedule">

      <header>
              <h2>{{monthName}} {{year}}</h2>
                    </header>
                    <table>
                          <tr>
                              <td>Sunday</td>
                              <td>Monday</td>
                              <td>Tuesday</td>
                              <td>Wednesday</td>
                              <td>Thursday</td>
                              <td>Friday</td>
                              <td>Saturday</td>
                        </tr>
                        {% for week in cal %}
                        <tr>
                            {% for day in week %}
                                {% if day %}
                                <td>
                                    {{ day }}<br />
                                    <input type="checkbox" name="{{ day }}" value="{{year}}/{{month}}" {% if day in PTO %}checked="checked"{%endif%}>
                                </td>
                                {% else %}
                                <td></td>
                                {% endif %}
                            {% endfor %}
                        </tr>
                        {% endfor %}
                    </table>
    </div>
    {% endif %}

{% endfor %}

{% endblock content %}

templates/base.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=1400, initial-scale=1.0">

        <link rel="stylesheet" href="/schedulingmedia/assets/css/header-basic-light.css">
        <link href='http://fonts.googleapis.com/css?family=Cookie' rel='stylesheet' type='text/css'>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>

        {% block code %}{% endblock code %}

        {% block css %}{% endblock css %}

        <title>{% block title %}{% endblock title %}</title>
    </head>

    <body>

        <header class="header-basic-light">
        
           <div class="header-limiter">
              {% if user.is_authenticated %}
      
                <h1>Hello, {{user.first_name}} {{user.last_name}}</h1>
                <nav>
                    <a href="/" class={% if request.resolver_match.url_name == "schedule" %}"selected"{% endif %}>Schedule</a>

                    {% if user.is_staff %}
                        <a href="/admin/">Admin</a>
                    {% endif %}

                    <a href="/pto/2018/3/" class={% if request.resolver_match.url_name == "pto" %}"selected"{% endif %}>PTO Requests</a>
                    <a href="/password_change/" class={% if request.resolver_match.url_name == "password_change" %}"selected"{% endif %}>Change Password</a>
                    <a href="/logout/">Logout</a>
                </nav>
    
            {% else %}      
                <nav>
                    <a href="/login/" class={% if request.resolver_match.url_name == "login" %}"selected"{% endif %}>Login</a>
                </nav>
   
            {% endif %}
      
         </div>
         
    </header>

    {% block content %}{% endblock content %}

    </body>
</html>

templates/calendar.html
{% extends "base.html" %}

{% block css %}
<link href='http://fonts.googleapis.com/css?family=PT+Sans:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=PT+Sans+Narrow:400,700' rel='stylesheet' type='text/css'>

<style>

/*body {
    line-height: 1;
    margin: 50px;
}*/

div.schedule {
    background: rgba(0, 0, 0, .1);
    border-radius: 5px;
    box-sizing: border-box;
    padding: 15px;
    width: 1050px;
    float:left;
    margin-top:20px;
    margin-left:50px;
}

div.key {
    border-radius: 5px;
    box-sizing: border-box;
    padding: 10px;
    margin-left: 20px;
    margin-top:30px;
    float:left;
}

header {
    overflow: clear;
    position: relative;
}

h2 {
    font-family: 'PT Sans Narrow', sans-serif;
    font-size: 18px;
    font-weight: 700;
    margin: 0 0 10px;
    text-align: center;
}

button {
    position: absolute;
    top: -4px;
}

button:first-child {
    left: 0;
}

button:last-child {
    right: 0;
}

table {
    background: #fff;
    border-collapse: collapse;
    color: #222;
    font-family: 'PT Sans', sans-serif;
    font-size: 13px;
    width: 100%;
}

td {
    border: 1px solid #ccc;
    color: #444;
    line-height: 22px;
    text-align: center;
    width: 150px;
    vertical-align: text-top;
    padding-top: 6px;
    padding-bottom: 5px;
}

tr:first-child td {
    color: #222;
    font-weight: 700;
}

.selected {
    background: #f0951d;
    border: 0;
    box-shadow: 0 2px 6px rgba(0, 0, 0, .5) inset;
}

/* Anesthesia + IR */
span.Anesthesia {
    background-color: #ffffff; 
}

/* Trauma */
span.Trauma {
    background-color: red;
}

/* Hepato */
span.Hepatobiliary {
    background-color: #9ACD32;
}

/* Orange */
span.Orange {
    background-color: orange;
}

/* Blue */
span.Blue {
    background-color: #6495ED;
}

/* Gold */
span.Gold {
    background-color: gold;
}

/* Breast */
span.Breast {
    background-color: #FF69B4;
}

/* Breast */
span.Colorectal {
    background-color: #000000;
    color: #ffffff;
}

/* PCH */
span.PCH {
    background-color: #BA55D3;
}

/* Vascular */
span.Vascular {
    background-color: #FFE4C4;
}

/* Harding */
span.Harding {
    background-color: #008B8B;
}

</style>

{% endblock css %}

{% block title %}{{ monthName }} - {{ year }}{% endblock title %}

{% block content %}

<div class="schedule">

  <header>
      {% if year == 2017 and lastMonth == 7 %}
      {% else %}
      <button onclick="location.href='http://stjoesscheduler.com/schedule/{{lastYear}}/{{lastMonth}}'">«</button>
      {% endif %}
          <h2>{{monthName}} {{year}}</h2>
      {% if year == 2018 and lastMonth == 1 %}
      {% else %}
          <button onclick="location.href='http://stjoesscheduler.com/schedule/{{nextYear}}/{{nextMonth}}'">»</button>
        {% endif %}
                </header>
                <table>
                      <tr style="height:20px;">
                          <td>Sunday</td>
                          <td>Monday</td>
                          <td>Tuesday</td>
                          <td>Wednesday</td>
                          <td>Thursday</td>
                          <td>Friday</td>
                          <td>Saturday</td>
                    </tr>
                    {% for week in schedule %}
                    <tr>
                        {% for day in week %}
                            {% if day.0 %}
                            <td style="height:75px;">
                                {{ day.0 }}<br />
                                {% for res, service in day.1 %}
                                <span id="{{service.onservice}}" class="{{service.get_onservice_display}}"><b>&nbsp;{{ res }}&nbsp;</b></span><br />
                                {% endfor %}
                                {% if day.2 %}
                                    PTO: {% for name in day.2 %}{{name}}{% if not forloop.last %}, {% endif %}{% endfor %}
                                {% endif %}
                            </td>
                            {% else %}
                            <td style="height:75px;">
                                <br />
                                {% if user.is_staff %}
                                    {% for res, service in day.1 %}
                                    <div style="opacity: 0.6;">&nbsp;{{ res }}&nbsp;<br /></div>
                                    {% endfor %}
                                {% endif %}
                            </td>
                            {% endif %}
                        {% endfor %}
                    </tr>
                    {% endfor %}
                </table>
</div>
              <div class="key">
                  <b>Service Key</b><br /><br />
                  <span class="Trauma">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span>&nbsp;&nbsp;Trauma<br /><br />
                  <span class="Gold">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span>&nbsp;&nbsp;Gen Surg Gold<br /><br />
                  <span class="Blue">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span>&nbsp;&nbsp;Gen Surg Blue<br /><br />
                  <span class="Orange">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span>&nbsp;&nbsp;Gen Surg Orange<br /><br />
                  <span class="Colorectal">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span>&nbsp;&nbsp;Colorectal<br /><br />
                  <span class="Vascular">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span>&nbsp;&nbsp;Vascular<br /><br />
                  <span class="Breast">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span>&nbsp;&nbsp;Breast<br /><br />
                  <span class="Hepatobiliary">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span>&nbsp;&nbsp;Hepatobiliary<br /><br />
                  <span class="Harding">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span>&nbsp;&nbsp;Harding<br /><br />
                  <span class="Anesthesia" style="border: 1px solid black;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span>&nbsp;&nbsp;Anesthesia<br /><br />
              </div>

              {% if user.is_staff %}            
                  <div class="key">
                      <b>PTO Request Conflicts</b><br /><br />
                  {% for day,residents,service in PTOConflictDays %}
                  <b>{{ day }}</b>: {% for res in residents %} <span class="{{service.get_onservice_display}}">{{ res.lname }}</span>{% if not forloop.last %},{% endif %} {% endfor %}<br /><br />
                  {% endfor %}
                  </div>
              {% endif %}

{% endblock content %}